### ISSUE TITLE
Tile Renderer occasionally stacktraces

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1010]
### Description

It looks as if certain conditions can cause a `NaN` to be passed as part of the projection translation into the renderer code for the background tiles. 

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome 115

### The OS you're using

MacOS 13.2

### Steps to reproduce

Visit someplace with an invalid mercator projection coord, such as http://localhost:8080/#background=stamen-terrain-background&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1933745&map=4.33/-90.000/143.536

Then examine the console.log to see the stack trace: 

`math.mjs:447 Uncaught RangeError: Invalid array length
    at range2 (math.mjs:447:21)
    at Tiler.getTiles (math.mjs:474:18)
    at PixiLayerBackgroundTiles.renderSource (PixiLayerBackgroundTiles.js:157:10)
    at PixiLayerBackgroundTiles.render (PixiLayerBackgroundTiles.js:91:12)
    at PixiScene.render (PixiScene.js:134:13)
    at PixiRenderer._app (PixiRenderer.js:417:16)
    at PixiRenderer._tick (PixiRenderer.js:250:14)
    at TickerListener.emit (TickerListener.ts:67:25)
    at _Ticker.update (Ticker.ts:427:37)
    at _tick (Ticker.ts:129:22)`

### The browser URL at the time you encountered the bug

http://localhost:8080/#background=stamen-terrain-background&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1933745&map=4.33/-90.000/143.536

**Comment by Bonkles** [comment]
Fixed in the above referenced issue-just an error in bookkeeping on my part.
