### ISSUE TITLE
Invalid projection causes Background tiles layer to stacktrace

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1026]
### Description

using normal map UI, whenever I resize the window or adjust the UI scaling in chrome I get: 

```
Uncaught RangeError RangeError: Invalid array length
    at range2 (/Users/clarkben/working/RapiD/node_modules/@rapid-sdk/math/built/math.mjs:447:21)
    at getTiles (/Users/clarkben/working/RapiD/node_modules/@rapid-sdk/math/built/math.mjs:473:18)
    at renderSource (/Users/clarkben/working/RapiD/modules/pixi/PixiLayerBackgroundTiles.js:162:10)
    at render (/Users/clarkben/working/RapiD/modules/pixi/PixiLayerBackgroundTiles.js:91:12)
    at render (/Users/clarkben/working/RapiD/modules/pixi/PixiScene.js:134:13)
    at _app (/Users/clarkben/working/RapiD/modules/pixi/PixiRenderer.js:432:16)
    at _tick (/Users/clarkben/working/RapiD/modules/pixi/PixiRenderer.js:265:14)
    at emit (/Users/clarkben/working/RapiD/node_modules/@pixi/ticker/src/TickerListener.ts:67:25)
```

If using the 3D Viewer, I get this instead:
![image](https://github.com/facebook/Rapid/assets/1887955/c22d339f-44bd-4f2e-9126-334759348e1b)

strongly suspect some projection tid\bit is getting NaN'd.
### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome v116.0

### The OS you're using

mac

### Steps to reproduce

While taking screenshots, I resized the map and got this stacktrace. 

### The browser URL at the time you encountered the bug

http://localhost:8080/#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.48/38.88927/-77.04978

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
Looks like a code refactor from a couple of months ago would cause an `Event` to get sent to the UiSystem.resize() method, which expects an offset to be sent to it, not an Event. 

This block would fire: 

```
    // When adjusting the sidebar width, pan the map so it stays centered on the same location.
    if (offset !== undefined) {
      map.pan(offset);
    }
```

And the map.pan() call, which expects an explicit x,y coord from the sidebar mouse event code, would completely hose the projection, causing this stack trace. 

Fix was to bind the resize handler in the map UI to explicitly call resize() not with the default Event, but with no params: 

i.e. from 
`window.addEventListener('resize', this.resize);`
to
`window.addEventListener('resize', () =>  this.resize());`

This caused `offset` to be undefined rather than an event, so the projection stays intact.
