### ISSUE TITLE
Walkthrough: During 'Points' step, hitting `Esc` or closing the sidebar with the mouse causes a catastrophic tight loop / soft crash.

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1043]
### Description

This only seems to happen in the 'When you are finished updating the cafe' step, but if you hit esc / the close X in the sidebar, rapid Freezes and the following gets console.logged endlessly:

```
TypeError: Cannot read properties of undefined (reading 'on')
    at /Users/clarkben/working/RapiD/modules/ui/intro/point.js:387:16
    at <anonymous> {stack: 'TypeError: Cannot read properties of undefine…80/dist/rapid.js:101003:18
    at <anonymous>', message: 'Cannot read properties of undefined (reading 'on')'}
```
![image](https://github.com/facebook/Rapid/assets/1887955/44323ce1-481e-4ad8-b24d-f2ba0e38233c)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome 116

### The OS you're using

MacOS 13.5

### Steps to reproduce

Get to the above step in the 'Points' section of the walkthrough, and hit `ESC` or click the X in the sidebar. 

Previous steps in both the navigation and points steps of the walkthroughs do NOT show this behavior. 

### The browser URL at the time you encountered the bug

n/a

**Comment by Bonkles** [comment]
Upon further inspection, this issue happens because of a bad reference to the UISystem's edit menu. The Line and Building steps are also affected.

**Comment by Bonkles** [comment]
Fix was extremely simple- lines, points, and building steps can now all be completed successfully.
