### ISSUE TITLE
`npm run quickstart` fails 

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1376]
I am following https://github.com/facebook/Rapid/blob/main/CONTRIBUTING.md#setting-up-rapid-locally but get the following error when running `npm run quickstart`. I did run `npm run all` before that. Tried it in a regular terminal as well as inside VS Code.

```console
% npm run quickstart

> @rapideditor/rapid@2.2.5 quickstart
> npm run start


> @rapideditor/rapid@2.2.5 start
> run-s build:css build:bundle start:server


> @rapideditor/rapid@2.2.5 build:css
> node scripts/build_css.js


🏗   Building css...
👍  css built: 96.153ms


> @rapideditor/rapid@2.2.5 build:bundle
> node config/esbuild.config.modern.js


  dist/rapid.js      4.7mb ⚠️
  dist/rapid.js.map  9.2mb

⚡ Done in 245ms

> @rapideditor/rapid@2.2.5 start:server
> node scripts/server.js

node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at StaticServer.start (/Users/…/Rapid/node_modules/static-server/server.js:111:58)
    at file:///Users/…/Rapid/scripts/server.js:14:8
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8080
}

Node.js v20.11.1
ERROR: "start:server" exited with 1.
```

### Version

- branch maproulette
- branch main

**Comment by bhousel** [comment]
Thanks, I'll fix this, it should just be `npm run start`.
(`quickstart` was from a long time ago when some of the build processes were slower before we switched to `esbuild`)
