### ISSUE TITLE
Area Drawing has issues using way segments to start or finish the area shape.

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#718]
If you start an area drawing gesture by clicking on an existing way segment, it SHOULD stitch a new node to the segment and then show you the polygon drawn from that new node to the mouse pointer. Instead, you get a single new node and a stack trace. 

https://user-images.githubusercontent.com/1887955/207385581-0c5b4dfe-faa9-4f1e-8b7a-cb20604202f8.mov

Stack trace is generated as soon as the user clicks to add the second vertex to the area: 

```
Uncaught TypeError TypeError: Cannot read properties of null (reading 'id')
    at _clickLoc (/Users/clarkben/working/RapiD/modules/modes/ModeDrawArea.js:264:52)
    at _click (/Users/clarkben/working/RapiD/modules/modes/ModeDrawArea.js:226:10)
    at emit (/Users/clarkben/working/RapiD/node_modules/eventemitter3/index.js:181:35)
    at _doClick (/Users/clarkben/working/RapiD/modules/behaviors/BehaviorDraw.js:303:10)
    at _pointerup (/Users/clarkben/working/RapiD/modules/behaviors/BehaviorDraw.js:213:12)
    at emit (/Users/clarkben/working/RapiD/node_modules/eventemitter3/index.js:181:35)
    at _pointerup (/Users/clarkben/working/RapiD/modules/pixi/PixiEvents.js:242:10)
    at notifyListeners (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:1313:26)
    at notifyTarget (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:549:18)
    at propagate (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:325:14)
    at dispatchEvent (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:240:14)
    at mapPointerUp (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:830:14)
    at mapEvent (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventBoundary.ts:261:28)
    at onPointerUp (/Users/clarkben/working/RapiD/node_modules/@pixi/events/src/EventSystem.ts:290:31)
_clickLoc @ /Users/clarkben/working/RapiD/modules/modes/ModeDrawArea.js:264:52
```

**Comment by Bonkles** [comment]
Fixed in `bd437d95c`. 

Here's a preview of the now-working functionality: 



https://user-images.githubusercontent.com/1887955/207411083-46801af5-65fd-4044-951a-07a6e6c9a7f0.mov
