### ISSUE TITLE
Need to update translations system with the latest transifex API calls

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#854]
As per https://github.com/openstreetmap/iD/commit/88d7d7f0507540c1a450dd4231d0555bfdda9acb, our `update_locales.js` script is out of date and throwing errors: 

```
404: https://www.transifex.com/api/2/project/id-editor/resource/core?details
404: https://www.transifex.com/api/2/project/id-editor/resource/imagery?details
404: https://api.transifex.com/organizations/openstreetmap/projects/id-editor/resources/core
404: https://www.transifex.com/api/2/project/id-editor/resource/community?details
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///Users/clarkben/working/RapiD/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
404: https://api.transifex.com/organizations/openstreetmap/projects/id-editor/resources/imagery
404: https://api.transifex.com/organizations/openstreetmap/projects/id-editor/resources/community
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///Users/clarkben/working/RapiD/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bhousel** [comment]
This is a good point that we need to update our Transifex API code, but to keep things simple I'm just going to close this and we can consider it as just the first part of solving #206
