### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#989]
### Description

Getting a blank shortcuts screen when I try to view the shorctuts help dialog. Also, after the first few calls to 'Cycle Highway Tags' causes the browser to seemingly soft-freeze, like the main rendering thread is completely blocked. 

When I open the shortcuts help dialog I see the following the stack trace: 

```
Uncaught TypeError TypeError: dataLoaderSystem.get is not a function
    at shortcutsModal (/Users/clarkben/working/RapiD/modules/ui/shortcuts.js:31:26)
    at call_default (/Users/clarkben/working/RapiD/node_modules/d3-selection/src/selection/call.js:4:12)
    at <anonymous> (/Users/clarkben/working/RapiD/modules/ui/shortcuts.js:263:29)
    at call_default (/Users/clarkben/working/RapiD/node_modules/d3-selection/src/selection/call.js:4:12)
    at clickShortcuts (/Users/clarkben/working/RapiD/modules/ui/panes/help.js:356:27)
    at <anonymous> (/Users/clarkben/working/RapiD/node_modules/d3-selection/src/selection/on.js:3:14)
```

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v114.0

### The OS you're using

mac

### The browser URL at the time you encountered the bug

http://127.0.0.1:8080/#background=Maxar-Premium&datasets=fbRoads,msBuildings&map=17.18/48.71813/3.26190

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
Okay, the problem with the soft-freeze was in the `entity_editor.js` file. 

Under the old d3_event system, repeatedly attaching the same event handler to an event was idempotent. Under the new EventEmitter regime, doing this will cause a separate instance of the handler to fire. 

If your event handler firing causes another event handler to get attached, you get an exponential storm of event handlers poppin' off. 

Solution was to put the event handler addition behind an _init variable to fire only once.
